import PDFDocument from 'pdfkit';
import type { Response } from 'express';

export interface PdfLine {
  product: string;
  qty: number;
  unitPrice: string;
  lineTotal: string;
}

export interface PdfPayload {
  documentTitle: string;
  documentNumber: string;
  date: string;
  status: string;
  currency: string;
  counterpartyLabel: string;
  counterpartyName: string;
  counterpartyDetails?: string[];
  lines: PdfLine[];
  subtotal: string;
  total: string;
  notes?: string | null;
  meta?: Array<{ label: string; value: string }>;
}

/**
 * Stream a clean A4 PDF for an order document (PO / SO) to the HTTP response.
 *
 * Kept intentionally framework-light: no external templating, just pdfkit
 * primitives. Output is deterministic for the given input — generated lazily
 * on each request, no caching.
 */
export function streamOrderPdf(res: Response, payload: PdfPayload): void {
  const fileName = `${payload.documentTitle.replace(/\s+/g, '-')}-${payload.documentNumber}.pdf`;
  res.setHeader('Content-Type', 'application/pdf');
  res.setHeader('Content-Disposition', `inline; filename="${fileName}"`);

  const doc = new PDFDocument({ size: 'A4', margin: 48 });
  doc.pipe(res);

  // Header
  doc.fontSize(18).fillColor('#0f5a3c').text('MedSupply Import & Distribution LLC', { align: 'left' });
  doc.moveDown(0.2);
  doc.fontSize(9).fillColor('#6b7280').text('US parent · Burkina Faso subsidiary', { align: 'left' });

  doc.moveDown(1);
  doc.fontSize(14).fillColor('#111827').text(`${payload.documentTitle} ${payload.documentNumber}`);
  doc.moveDown(0.3);
  doc.fontSize(10).fillColor('#6b7280').text(`Date: ${payload.date}    Status: ${payload.status}    Currency: ${payload.currency}`);

  // Counterparty
  doc.moveDown(1);
  doc.fontSize(11).fillColor('#111827').text(payload.counterpartyLabel, { underline: true });
  doc.fontSize(10).text(payload.counterpartyName);
  for (const line of payload.counterpartyDetails ?? []) {
    if (line) doc.text(line);
  }

  // Meta rows
  if (payload.meta && payload.meta.length) {
    doc.moveDown(0.8);
    for (const row of payload.meta) {
      doc.fontSize(10).fillColor('#6b7280').text(`${row.label}: `, { continued: true });
      doc.fillColor('#111827').text(row.value);
    }
  }

  // Lines table
  doc.moveDown(1);
  const tableTop = doc.y;
  const colX = { product: 48, qty: 320, price: 380, total: 470 };
  doc.fontSize(10).fillColor('#111827');
  doc.text('Product', colX.product, tableTop);
  doc.text('Qty', colX.qty, tableTop, { width: 40, align: 'right' });
  doc.text('Unit price', colX.price, tableTop, { width: 80, align: 'right' });
  doc.text('Line total', colX.total, tableTop, { width: 80, align: 'right' });
  doc.moveTo(48, tableTop + 14).lineTo(547, tableTop + 14).strokeColor('#d1d5db').stroke();

  let y = tableTop + 20;
  for (const line of payload.lines) {
    if (y > 720) {
      doc.addPage();
      y = 48;
    }
    doc.fontSize(10).fillColor('#111827').text(line.product, colX.product, y, { width: 260 });
    doc.text(String(line.qty), colX.qty, y, { width: 40, align: 'right' });
    doc.text(line.unitPrice, colX.price, y, { width: 80, align: 'right' });
    doc.text(line.lineTotal, colX.total, y, { width: 80, align: 'right' });
    y += 18;
  }

  doc.moveTo(48, y + 4).lineTo(547, y + 4).strokeColor('#d1d5db').stroke();
  y += 12;
  doc.fontSize(10).fillColor('#6b7280').text('Subtotal', colX.price, y, { width: 80, align: 'right' });
  doc.fillColor('#111827').text(payload.subtotal, colX.total, y, { width: 80, align: 'right' });
  y += 16;
  doc.fontSize(11).fillColor('#111827').text('Total', colX.price, y, { width: 80, align: 'right' });
  doc.text(`${payload.total} ${payload.currency}`, colX.total, y, { width: 80, align: 'right' });

  if (payload.notes) {
    y += 32;
    if (y > 720) {
      doc.addPage();
      y = 48;
    }
    doc.fontSize(10).fillColor('#111827').text('Notes', 48, y);
    doc.fontSize(9).fillColor('#6b7280').text(payload.notes, 48, y + 14, { width: 500 });
  }

  // Footer
  doc.fontSize(8).fillColor('#9ca3af').text(
    'Generated by the MedSupply Import & Distribution LLC Portal · WHO-GMP sourced · DGPML compliant',
    48,
    780,
    { align: 'center', width: 500 },
  );

  doc.end();
}
